#!/bin/sh
logger "Applying firewall-start rules"
iptables -I FORWARD -d 8.8.8.8 -j REJECT
iptables -I FORWARD -d 8.8.4.4 -j REJECT
ip6tables -I FORWARD -d 2001:4860:4860::/48 -j REJECT

#sh /jffs/scripts/download-upload-fix &
sh /jffs/scripts/key-qos &


#source
iptables -t mangle -A PREROUTING -p UDP -m multiport --sports 500,4500 -j TOS --set-tos 0x16
ip6tables -t mangle -A PREROUTING -p UDP -m multiport --sports 500,4500 -j TOS --set-tos 0x16
#destination
iptables -t mangle -A PREROUTING -p UDP -m multiport --dports 500,4500 -j TOS --set-tos 0x16
ip6tables -t mangle -A PREROUTING -p UDP -m multiport --dports 500,4500 -j TOS --set-tos 0x16

#comcast change dscp
#iptables -t mangle -A PREROUTING -i eth0 -p all -j DSCP --set-dscp 0
#ip6tables -t mangle -A PREROUTING -i eth0 -p all -j DSCP --set-dscp 0

#iptables -t mangle -A PREROUTING -i eth0 -p all -j TOS --set-tos 0x0
#ip6tables -t mangle -A PREROUTING -i eth0 -p all -j TOS --set-tos 0x0

#iptables -t mangle -A FORWARD -i eth0 -p all -j DSCP --set-dscp 0
#ip6tables -t mangle -A FORWARD -i eth0 -p all -j DSCP --set-dscp 0
#iptables -t mangle -A FORWARD -i eth0 -p all -j TOS --set-tos 0x0
#ip6tables -t mangle -A FORWARD -i eth0 -p all -j TOS --set-tos 0x0

#iptables -t mangle -A POSTROUTING -o br0 -p all -j DSCP --set-dscp 0
#ip6tables -t mangle -A POSTROUTING -o br0 -p all -j DSCP --set-dscp 0
#iptables -t mangle -A POSTROUTING -o br0 -p all -j TOS --set-tos 0x0
#ip6tables -t mangle -A POSTROUTING -o br0 -p all -j TOS --set-tos 0x0

