#!/bin/sh

# rate limit + classless qos
modprobe ipt_TOS
modprobe ipt_tos
modprobe xt_dscp
ifconfig eth0 txqueuelen 128
ifconfig eth1 txqueuelen 128
ifconfig eth2 txqueuelen 128
ifconfig fwd0 txqueuelen 128
ifconfig fwd1 txqueuelen 128
ifconfig br0 txqueuelen 128

tc qdisc replace dev eth0 root handle 1: prio
tc qdisc add dev eth0 parent 1:1 handle 10: tbf rate 20Mbit latency 20ms burst 64kb mpu 82 mtu 20000
tc qdisc add dev eth0 parent 10: handle 100: sfq headdrop
tc qdisc add dev eth0 parent 1:2 handle 11: tbf rate 20Mbit latency 20ms burst 512kb mpu 82 mtu 20000
tc qdisc add dev eth0 parent 11: handle 110: sfq headdrop
tc qdisc add dev eth0 parent 1:3 handle 12: tbf rate 20Mbit latency 20ms burst 512kb mpu 82 mtu 20000
tc qdisc add dev eth0 parent 12: handle 120: sfq headdrop

#tc qdisc replace dev br0 root handle 2: fq_codel limit 128 flows 1024 ecn
tc qdisc replace dev br0 root handle 2: prio
tc qdisc add dev br0 parent 2:1 handle 20: sfq headdrop
tc qdisc add dev br0 parent 2:2 handle 21: sfq headdrop
tc qdisc add dev br0 parent 2:3 handle 22: sfq headdrop

#tc qdisc replace dev fwd0 root handle 3: prio
#tc qdisc add dev fwd0 parent 3:1 handle 30: sfq headdrop
#tc qdisc add dev fwd0 parent 3:2 handle 31: sfq headdrop
#tc qdisc add dev fwd0 parent 3:3 handle 32: sfq headdrop

#tc qdisc replace dev fwd1 root handle 4: prio
#tc qdisc add dev fwd1 parent 4:1 handle 40: sfq headdrop
#tc qdisc add dev fwd1 parent 4:2 handle 41: sfq headdrop
#tc qdisc add dev fwd1 parent 4:3 handle 42: sfq headdrop

#tc qdisc replace dev eth1 root handle 5: prio
#tc qdisc add dev eth1 parent 5:1 handle 50: sfq headdrop
#tc qdisc add dev eth1 parent 5:2 handle 51: sfq headdrop
#tc qdisc add dev eth1 parent 5:3 handle 52: sfq headdrop

#tc qdisc replace dev eth2 root handle 6: prio
#tc qdisc add dev eth2 parent 6:1 handle 60: sfq headdrop
#tc qdisc add dev eth2 parent 6:2 handle 61: sfq headdrop
#tc qdisc add dev eth2 parent 6:3 handle 62: sfq headdrop

#Rehash everything with NAT support

tc filter add dev eth0 parent 100: handle 111 pref 10 flow hash keys nfct-src,nfct-dst,proto,nfct-proto-src,nfct-proto-dst perturb 30 divisor 1024
tc filter add dev eth0 parent 110: handle 112 pref 10 flow hash keys nfct-src,nfct-dst,proto,nfct-proto-src,nfct-proto-dst perturb 30 divisor 1024
tc filter add dev eth0 parent 120: handle 113 pref 10 flow hash keys nfct-src,nfct-dst,proto,nfct-proto-src,nfct-proto-dst perturb 30 divisor 1024

###### FQ-CODEL #######
#tc filter add dev br0 parent 2: handle 2 pref 10 flow hash keys nfct-src,nfct-dst,proto,nfct-proto-src,nfct-proto-dst perturb 30 divisor 1024

###### SFQ #####
tc filter add dev br0 parent 20: handle 121 pref 10 flow hash keys nfct-src,nfct-dst,proto,nfct-proto-src,nfct-proto-dst perturb 30 divisor 1024
tc filter add dev br0 parent 21: handle 122 pref 10 flow hash keys nfct-src,nfct-dst,proto,nfct-proto-src,nfct-proto-dst perturb 30 divisor 1024
tc filter add dev br0 parent 22: handle 123 pref 10 flow hash keys nfct-src,nfct-dst,proto,nfct-proto-src,nfct-proto-dst perturb 30 divisor 1024

#tc filter add dev fwd0 parent 30: handle 111 pref 10 protocol all flow hash keys nfct-src,nfct-dst,proto,nfct-proto-src,nfct-proto-dst perturb 30 divisor 1024
#tc filter add dev fwd0 parent 31: handle 112 pref 10 protocol all flow hash keys nfct-src,nfct-dst,proto,nfct-proto-src,nfct-proto-dst perturb 30 divisor 1024
#tc filter add dev fwd0 parent 32: handle 113 pref 10 protocol all flow hash keys nfct-src,nfct-dst,proto,nfct-proto-src,nfct-proto-dst perturb 30 divisor 1024

#tc filter add dev fwd1 parent 40: handle 111 pref 10 protocol all flow hash keys nfct-src,nfct-dst,proto,nfct-proto-src,nfct-proto-dst perturb 30 divisor 1024
#tc filter add dev fwd1 parent 41: handle 112 pref 10 protocol all flow hash keys nfct-src,nfct-dst,proto,nfct-proto-src,nfct-proto-dst perturb 30 divisor 1024
#tc filter add dev fwd1 parent 42: handle 113 pref 10 protocol all flow hash keys nfct-src,nfct-dst,proto,nfct-proto-src,nfct-proto-dst perturb 30 divisor 1024

#tc filter add dev eth1 parent 50: handle 111 pref 10 protocol all flow hash keys nfct-src,nfct-dst,proto,nfct-proto-src,nfct-proto-dst perturb 30 divisor 1024
#tc filter add dev eth1 parent 51: handle 112 pref 10 protocol all flow hash keys nfct-src,nfct-dst,proto,nfct-proto-src,nfct-proto-dst perturb 30 divisor 1024
#tc filter add dev eth1 parent 52: handle 113 pref 10 protocol all flow hash keys nfct-src,nfct-dst,proto,nfct-proto-src,nfct-proto-dst perturb 30 divisor 1024

#tc filter add dev eth2 parent 60: handle 111 pref 10 protocol all flow hash keys nfct-src,nfct-dst,proto,nfct-proto-src,nfct-proto-dst perturb 30 divisor 1024
#tc filter add dev eth2 parent 61: handle 112 pref 10 protocol all flow hash keys nfct-src,nfct-dst,proto,nfct-proto-src,nfct-proto-dst perturb 30 divisor 1024
#tc filter add dev eth2 parent 62: handle 113 pref 10 protocol all flow hash keys nfct-src,nfct-dst,proto,nfct-proto-src,nfct-proto-dst perturb 30 divisor 1024

conntrack -F
